### ISSUE TITLE
Fill and Submit a Collaboration Form

### ISSUE THREAD

**Issue by arathivariar** [arathivariar/kerala-kitchen-kaleidoscope#14]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Contact Us |
| Epic | Collaboration Form  |
| User Story | Fill and Submit a Collaboration Form  |

As a **Potential Collaborator** I can **fill in a contact form** so that **I can submit a collaboration request**

- Acceptance criteria 1: The user can fill in a form with his details like name, email address, and a message (can be a new recipe)

- Acceptance criteria 2: The user can submit the filled form.

- Acceptance criteria 3: The user gets a confirmation message after submitting successfully.

## Tasks
- [ ] Create a form with the required fields like name, email address, and message.
- [ ] The user fills in the form.
- [ ] Validate the user inputs.
- [ ] The user submits the form and a confirmation message is displayed.
