### ISSUE TITLE
Edit Comment

### ISSUE THREAD

**Issue by arathivariar** [arathivariar/kerala-kitchen-kaleidoscope#15]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | User Action  |
| Epic |  User Action |
| User Story | Edit Comment |

As a **user** I can **click on the edit button of my  comment** so that I can **edit the comment and save it again**

- Acceptance criteria 1: The user can click the edit button and edit the comment.

- Acceptance criteria 2: The updated comment is saved and displayed.

## Tasks
- [x] Add an edit button to edit the comments
- [x] The user can edit the comment
- [x] The edited comment is updated and saved
- [x] The updated comment is displayed

**Comment by arathivariar** [comment]
The user story is completed as the following acceptance criteria are met:

- Acceptance criteria 1: The user can click the edit button and edit the comment.

- Acceptance criteria 2: The updated comment is saved and displayed.
