### ISSUE TITLE
User Registration

### ISSUE THREAD

**Issue by arathivariar** [arathivariar/kerala-kitchen-kaleidoscope#5]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | User Account |
| Epic |  User Profile |
| User Story | User Registration |

As a **user** I can **enter my email ID and password** so that **register an account with the website**

- Acceptance criteria 1: The user can create an account by entering their email ID and password

## Tasks
- [x]  Create a Sign-Up feature for user registration
- [x]  The user enters their email ID and password as credentials
- [x]  The user account is created
- [x]  The user can login to the website after signing up

**Comment by arathivariar** [comment]
The user story for User Registration is completed.
