### ISSUE TITLE
User Login

### ISSUE THREAD

**Issue by arathivariar** [arathivariar/kerala-kitchen-kaleidoscope#6]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | User Account |
| Epic | User Profile  |
| User Story | Login |

As a **user** I can **use my email ID and password to log in to my profile account** so that **I can use my profile to access the website's features**

- Acceptance criteria 1: The user can log in to the website with his credentials.

- Acceptance criteria 2: The user can access the website's features after logging in.

## Tasks
- [x] Create the login functionality for the user.
- [x] The user should enter the registered email ID and password.
- [x] After logging in, the user can access the website's features.

**Comment by arathivariar** [comment]
The user story for User Login is completed.
