### ISSUE TITLE
User Log Out

### ISSUE THREAD

**Issue by arathivariar** [arathivariar/kerala-kitchen-kaleidoscope#8]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | User Account |
| Epic | User Profile  |
| User Story | User Log Out |

As a **user** I can **receive feedback in the form of a logout message** so that **I can confirm that I have been logged out successfully**

- Acceptance criteria 1: The user can log out of their account.

- Acceptance criteria 2: The user gets a confirmation in the form of a feedback message after logging out successfully.

## Tasks
- [x] The user clicks logout button.
- [x]  A feedback message is displayed for successful logout.
- [x] The user is logged out.

**Comment by arathivariar** [comment]
The user story for User Log Out is completed.
